### ISSUE TITLE
Mod Menu bug

### ISSUE THREAD

**Issue by horseloyal** [Ryhon0/SimpleAutoswitch#1]
![image](https://github.com/Ryhon0/SimpleAutoswitch/assets/171438743/fd6c7ebf-f9bd-4b23-bdde-c51a440c4cca)

**Comment by Ryhon0** [comment]
Which version of Minecraft and Simple Autoswitch is this? Doesn't seem to happen on 1.20.6 with 1.1.0 for me

**Comment by horseloyal** [comment]
> Which version of Minecraft and Simple Autoswitch is this? Doesn't seem to happen on 1.20.6 with 1.1.0 for me

1.0.1 (the version on modrinth) on 1.20.6

**Comment by Ryhon0** [comment]
My bad, I meant Autoswitch 1.0.1.
Which version of Fabric loader, Fabric API and Mod Menu are you using?
Can you update the loader to 0.15.11, Fabric API to 0.98.0 and ModMenu to 10.0.0-beta.1?

**Comment by horseloyal** [comment]
My Fabric loader version is already 0.15.11, my fabric API version is 0.99.4, and my mod menu version is 10.0.0-beta.1. 

Fabric API 0.98.0 is incompatible with 1.20.6?

**Comment by Ryhon0** [comment]
I created a fresh instance and can confirm this bug but adding mods from the other instance magically fixes it. I'll figure out which mod is that and add it to the dependencies

**Comment by Ryhon0** [comment]
Can you try this version? Seems to be fixed for me
[simple-autoswitch-1.0.2.zip](https://github.com/user-attachments/files/15594600/simple-autoswitch-1.0.2.zip)

**Comment by horseloyal** [comment]
Works for me 100%, thanks for taking the time out of your day to maintain this mod for everyone.
