### ISSUE TITLE
Append Minecraft version to version field in FMJ

### ISSUE THREAD

**Issue by Poopooracoocoo** [Ryhon0/SimpleAutoswitch#6]
Because you have the same version for multiple Minecraft versions, you cannot tell which exact version someone has by looking at the mod list in a log. 

![Screenshot_20241201_115103_Chrome](https://github.com/user-attachments/assets/56a0d654-4c1b-4d45-b84e-08fae4787b9e)

Sodium, for example, does 0.6.0+mc1.21.1. Similarly Fabric API does 0.109.0+1.21.3. 

A tight Minecraft dependency is also a good solution.

**Comment by Ryhon0** [comment]
This is not something I'm interested in.
If a new Minecraft version releases and the mod is compatible out of the box, the version will be added to the Modrinth versions, thus there will be no dependency on a Minecraft version.
