### ISSUE TITLE
Settings screen not working (Minecraft 1.21.4

### ISSUE THREAD

**Issue by BrockBoB** [Ryhon0/SimpleAutoswitch#7]
The settings screen in Minecraft version 1.21.4 doesn't work, clicking any of the options simply does nothing and doesn't change the value from true to false, only the toggle works by pressing the "V" key as per keyboard shortcut.

![image](https://github.com/user-attachments/assets/301362da-610c-40ed-8652-737c4ae6e2a1)

**Comment by Ryhon0** [comment]
My bad, will fix soon

**Comment by Ryhon0** [comment]
Should be fixed in 1.2.0 now

**Comment by BrockBoB** [comment]
> Should be fixed in 1.2.0 now

Thank you very much! Did you also remove the option to "Require Attack Button to Be Held"? I found that really useful :/

**Comment by Ryhon0** [comment]
Yes as I don't see it being useful and was broken
